Data analysis of the data

### prognosis

lieve=mild

death no in the test set

[intro video](https://covidcxr-hackathon.slack.com/files/U03010UC79D/F031AKQC3EJ/hackathon_presentation_v2.mp4) 

In [8]:
import pandas as pd
import numpy as np
from PIL import Image
import os
from sklearn import preprocessing

## Clinical data

In [3]:
data_path= r'TrainSet/trainClinData.xls'
df= pd.read_excel(data_path)
print(df.shape)
df.head()

(1103, 40)


Row_number  ImageFile Hospital        Age  Sex  PositivityAtAdmission  \
0          82  P_102.png        A  72.000000    1                    1.0   
1         228  P_131.png        D  35.913889    0                    1.0   
2         229  P_132.png        D  57.266667    0                    1.0   
3          96  P_117.png        A  39.000000    1                    1.0   
4         112   P_16.png        A  44.000000    0                    1.0   

   Temp_C  DaysFever  Cough  DifficultyInBreathing  ...  Diabetes  Dementia  \
0    37.3        3.0    1.0                    0.0  ...       0.0       0.0   
1    39.3        3.0    1.0                    0.0  ...       0.0       0.0   
2    37.0        3.0    0.0                    0.0  ...       0.0       0.0   
3    37.2        2.0    1.0                    0.0  ...       0.0       0.0   
4    38.0        3.0    1.0                    0.0  ...       0.0       0.0   

   BPCO  Cancer  ChronicKidneyDisease  RespiratoryFailure  Obesity  Position  \
0   0.0     1.0                   0.0                 0.0      0.0       0.0   
1   0.0     0.0                   0.0                 NaN      1.0       0.0   
2   0.0     0.0                   0.0                 NaN      NaN       0.0   
3   0.0     0.0                   0.0                 0.0      0.0       1.0   
4   0.0     0.0                   0.0                 0.0      0.0       0.0   

   Prognosis  Death  
0     SEVERE      0  
1       MILD      0  
2       MILD      0  
3       MILD      0  
4     SEVERE      0  

[5 rows x 40 columns]

In [7]:
np.unique(df.Death, return_counts=True)


(array([0, 1], dtype=int64), array([910, 193], dtype=int64))

In [6]:
# balanced dataset on the object class
np.unique(df.Prognosis, return_counts=True)

(array(['MILD', 'SEVERE'], dtype=object), array([535, 568], dtype=int64))

In [13]:
le = preprocessing.LabelEncoder()
binarial_Prognosis=le.fit_transform(df.Prognosis)
le.classes_

array(['MILD', 'SEVERE'], dtype=object)

In [12]:
df_order= df.sort_values(by=['Row_number'])
df_order

Row_number    ImageFile Hospital        Age  Sex  PositivityAtAdmission  \
286            1      P_1.png        A  38.000000    0                    1.0   
879            2     P_33.png        A  49.000000    0                    1.0   
343            3     P_44.png        A  41.000000    0                    1.0   
105            4     P_55.png        A  67.000000    0                    1.0   
428            5     P_66.png        A  39.000000    1                    1.0   
...          ...          ...      ...        ...  ...                    ...   
1088        1112  P_2_118.png        C  82.127310    1                    1.0   
535         1113  P_2_119.png        C  76.279261    1                    1.0   
1089        1114  P_2_120.png        C  58.598220    1                    1.0   
1095        1115  P_2_121.png        C  78.335387    0                    1.0   
525         1116  P_2_122.png        C  80.197125    1                    1.0   

      Temp_C  DaysFever  Cough  DifficultyInBreathing  ...  Diabetes  \
286     36.0        4.0    1.0                    0.0  ...       0.0   
879     37.5        2.0    1.0                    1.0  ...       0.0   
343     36.0        3.0    1.0                    0.0  ...       0.0   
105     36.7        2.0    1.0                    1.0  ...       0.0   
428     37.3        1.0    1.0                    0.0  ...       0.0   
...      ...        ...    ...                    ...  ...       ...   
1088    36.8        NaN    0.0                    0.0  ...       NaN   
535     36.2        NaN    1.0                    1.0  ...       NaN   
1089    38.0        NaN    1.0                    1.0  ...       NaN   
1095    38.0        NaN    0.0                    1.0  ...       NaN   
525     36.5        NaN    0.0                    1.0  ...       NaN   

      Dementia  BPCO  Cancer  ChronicKidneyDisease  RespiratoryFailure  \
286        0.0   0.0     0.0                   0.0                 0.0   
879        0.0   0.0     0.0                   0.0                 0.0   
343        0.0   0.0     0.0                   0.0                 0.0   
105        0.0   0.0     1.0                   0.0                 0.0   
428        0.0   0.0     0.0                   0.0                 0.0   
...        ...   ...     ...                   ...                 ...   
1088       NaN   NaN     NaN                   NaN                 NaN   
535        NaN   NaN     NaN                   NaN                 NaN   
1089       NaN   NaN     NaN                   NaN                 NaN   
1095       NaN   NaN     NaN                   NaN                 NaN   
525        NaN   NaN     NaN                   NaN                 NaN   

      Obesity  Position  Prognosis  Death  
286       0.0       1.0       MILD      0  
879       0.0       1.0     SEVERE      0  
343       0.0       1.0       MILD      0  
105       1.0       1.0     SEVERE      0  
428       0.0       1.0       MILD      0  
...       ...       ...        ...    ...  
1088      NaN       NaN     SEVERE      0  
535       NaN       NaN     SEVERE      1  
1089      NaN       NaN     SEVERE      1  
1095      NaN       NaN     SEVERE      1  
525       NaN       NaN     SEVERE      1  

[1103 rows x 40 columns]

In [ ]:
df_order.reset_index(inplace=True, drop=True)

In [ ]:
df_order

In [14]:
np.unique(df.Row_number)

array([   1,    2,    3, ..., 1114, 1115, 1116], dtype=int64)

## X-rays images

open the different images

In [13]:
img= Image.open(r'TrainSet\TrainSet\P_833.png')
print(img.size)
img.show()

(2836, 2336)


In [17]:
data = np.asarray(img)
data.shape
data

array([[12497, 12476, 12476, ..., 16383, 16383, 16383],
       [12476, 12474, 12472, ..., 16383, 16383, 16383],
       [12468, 12464, 12464, ..., 16383, 16383, 16383],
       ...,
       [16383, 16383, 16383, ..., 16383, 16383, 16383],
       [16383, 16383, 16383, ..., 16383, 16383, 16383],
       [16383, 16383, 16383, ..., 16383, 16383, 16383]])